<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class WaitList extends Model
{
    use HasFactory;

    protected $fillable = ['first_name', 'last_name', 'email', 'country', 'referrer_code', 'referred_by', 'code_used'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function ($model) {
            $model->referrer_code = Str::random(20);
        });
    }

    public function sendWelcomeMail()
    {

    }
}


